---
# tasks file for ansible-christian-server

- name: Ensure, that all packages are updated and upgraded.
  apt:
    upgrade: "yes"
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: Ensure that initial packages are installed.
  apt:
    name: "{{ initial_packages }}"
    state: present

# see also https://github.com/holms/ansible-fqdn
- name: Set hostname.
  hostname:
    name: "{{ base_hostname }}"
  notify:
    - restart systemd-logind

- name: Copy hosts file with FQDN and hostname.
  template:
    src: hosts.j2
    dest: /etc/hosts
  notify:
    - restart systemd-logind

- name: Set timezone.
  timezone:
    name: "{{ base_timezone }}"

- name: Create a nice message of the day graphic and a greeting.
  template:
    src: motd.j2
    dest: /etc/motd

- name: Show the motd after login.
  copy:
    src: 20-motd-welcome
    dest: /etc/update-motd.d/20-motd-welcome

- name: Add users.
  user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    shell: /bin/bash
  with_items: "{{ base_users }}"

- name: Add public keys for users.
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.key }}"
  with_items: "{{ base_users }}"

- name: Add public key for root.
  authorized_key:
    user: root
    key: "{{ base_root_key }}"

- name: Copy bashrc for each user.
  copy:
    src: users.bashrc
    dest: "/home/{{ item.name }}/.bashrc"
  with_items: "{{ base_users }}"

- name: Copy customized root bashrc.
  copy:
    src: bashrc
    dest: /root/.bashrc

- name: Copy profile.d with verse and history
  template:
    src: profile_verse_history.sh.j2
    dest: /etc/profile.d/profile_verse_history.sh
